# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2481685f14329c874883eaae804b957383da60f7253ffd538d0ad6568bc88f8de3500c8b4f0408349218a809aee7c67f73e717e0e7504ebe16822dedce36b528

test:
  secret_key_base: 2bbb2f1c626d12b54046e8ae3408b08c82648b40d66cf0ca0921c267aecd3f4c11d65ac944bab766b705bf99e521b279440386ac2a17e81a7eec9043d7de6c9c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
